#pragma once

template <class T>
class CProxy_IXSHEvents : public IConnectionPointImpl<T, &__uuidof( _IXSHEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
