#pragma once

template <class T>
class CProxy_IXScriptHostEvents : public IConnectionPointImpl<T, &__uuidof( _IXScriptHostEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
