local Helper = XLGetGlobal("Helper")

local TOKEN = {
	["DOWNLOAD_SERVERCONFIG_FILE"] = 10000,
	["DOWNLOAD_EXTRACODE_FILE"]   = 10001,
	["DOWNLOAD_MANUALUPDATE_FILE"] = 10002,
	["DOWNLOAD_FORECUPDATE_FILE"]  = 10003,
}
Helper.TOKEN = TOKEN